/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author tylerliu
 */
public class CourseIcon extends javax.swing.JPanel {

    private Course course;
    private CoursePanel coursePanel;
    /**
     * Creates new form CourseIcon
     */
    public CourseIcon(CoursePanel coursePanel, String name, Course course) {
        initComponents();
        setCourseNameTxt(name);
        this.course = course;
        this.coursePanel = coursePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseNameTxt = new javax.swing.JTextField();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelPressed(evt);
            }
        });

        courseNameTxt.setEditable(false);
        courseNameTxt.setBackground(new java.awt.Color(51, 51, 51));
        courseNameTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        courseNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                courseNameTxtPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(courseNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(courseNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPressed
        System.out.println("Pressed");
    }//GEN-LAST:event_panelPressed

    private void courseNameTxtPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseNameTxtPressed
        System.out.println(courseNameTxt.getText() + " Pressed");
        TopicListPanel tp = new TopicListPanel(coursePanel, course);
        //tp.setSize(coursePanel.getSize());
        coursePanel.removeAll();

        coursePanel.add(tp);
        coursePanel.validate();
        coursePanel.repaint();
    }//GEN-LAST:event_courseNameTxtPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseNameTxt;
    // End of variables declaration//GEN-END:variables

    public void setCourseNameTxt(String name) {
        courseNameTxt.setText(name);
        courseNameTxt.setForeground(Color.WHITE);
        courseNameTxt.setFont(new Font("Helvetica Neue", Font.PLAIN, 24));
    }
   

}
