import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author tylerliu
 */
public class ProfilePanel extends javax.swing.JPanel {

    private CoursePanel coursePanel;
    private Question mostWrong;
    //private JPanel mainPanel;
    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel(CoursePanel cp) throws java.io.IOException {
        initComponents();
        coursePanel = cp;
        //this.mainPanel = mainPanel;
        //setSize(mainPanel.getSize());
        mostWrong = FileRead.getMostWrong();
        
        if (mostWrong != null) {
            String mw = "";
            jButton1.setVisible(true);
            if (mostWrong.getQuestionTopic() instanceof Quadratic && mostWrong.getQuestionType() == 1) {
                mw = "x-intercepts for quadratics";
            }
            else if (mostWrong.getQuestionTopic() instanceof Quadratic && mostWrong.getQuestionType() == 2) {
                mw = "factors for quadratics";
            }
            else if (mostWrong.getQuestionTopic() instanceof Linear && mostWrong.getQuestionType() == 1) {
                mw = "slope for linear equations";
            }
            else if (mostWrong.getQuestionTopic() instanceof Linear && mostWrong.getQuestionType() == 2) {
                mw = "intersections of linear equations";
            }

            jTextField2.setText("We noticed you tend to miss questions about " + mw + ". Do you want to take a quiz about " + mw + "?");
        }
        else {
            jTextField2.setText("Congrats! You have not gotten a question wrong so far!");
            jButton1.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Profile");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        jButton1.setText("Create Quiz");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jTextField2)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        // generate Quiz (placeholder quadratic)
        System.out.println("click here pressed");
        Quiz quiz = null;
        
        if (mostWrong.getQuestionTopic() instanceof Quadratic && mostWrong.getQuestionType() == 1) {
            quiz = mostWrong.getQuestionTopic().getQuiz(1);
        }
        else if (mostWrong.getQuestionTopic() instanceof Quadratic && mostWrong.getQuestionType() == 2) {
            quiz = mostWrong.getQuestionTopic().getQuiz(2);
        }
        else if (mostWrong.getQuestionTopic() instanceof Linear && mostWrong.getQuestionType() == 1) {
            quiz = mostWrong.getQuestionTopic().getQuiz(1);
        }
        else if (mostWrong.getQuestionTopic() instanceof Linear && mostWrong.getQuestionType() == 2) {
            quiz = mostWrong.getQuestionTopic().getQuiz(2);
        }
        
        QuizPanel qp = new QuizPanel(coursePanel, quiz);
        
        
        coursePanel.removeAll();
        //mainPanel.removeAll();
        coursePanel.add(qp);
        coursePanel.validate();
        coursePanel.repaint();
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
