/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author tylerliu
 */
public class QuizPanel extends javax.swing.JPanel implements java.awt.event.ActionListener {

    private Quiz quiz;
    private JButton submitBtn;
    private ArrayList<QuestionPanel> questionPanels = new ArrayList<QuestionPanel>();
    private JTextField header;
    private CoursePanel coursePanel;
    /**
     * Creates new form QuizPanel
     */
    public QuizPanel(CoursePanel coursePanel, Quiz quiz) {
        initComponents();
        GridLayout gl = new GridLayout();
        gl.setRows(7);
        setLayout(gl);

        this.quiz = quiz;
        this.coursePanel = coursePanel;
        
        header = new JTextField(quiz.getQuestions().get(0).getQuestionTopic().getName() + " Quiz");
        header.setBackground(new Color(51, 51, 51));
        header.setHorizontalAlignment(JTextField.CENTER);
        header.setBorder(null);
        header.setEditable(false);
        header.setForeground(Color.WHITE);
        header.setFont(new Font("Helvetica Neue", Font.PLAIN, 24));
        
        add(header);
        
        addQuestions();
        addSubmitBtn();
    }

    private void addQuestions() {
        System.out.println("addQuestions called");
        ArrayList<Question> questions = quiz.getQuestions();
        System.out.println(questions.size());
        for (int i = 0; i < questions.size(); i++) {
            QuestionPanel qp = new QuestionPanel(questions.get(i));
            add(qp);
            questionPanels.add(qp);
        }
        
    }
    
    private void addSubmitBtn() {
        submitBtn = new JButton();
        submitBtn.setSize(200, 200);
        submitBtn.setText("Submit Answers");
        submitBtn.addActionListener(this);
        add(submitBtn);
    }
    
    public void actionPerformed(java.awt.event.ActionEvent e) {
        if (e.getSource() == submitBtn) {
            System.out.println("submitted quiz");
            
            // TODO check answers and generate results page
            ArrayList<String> studentAnswers = new ArrayList<String>();
            for (int i = 0; i < questionPanels.size(); i++) {
                studentAnswers.add(questionPanels.get(i).getAnswerTxt());
            }
            ResultsPanel rp = new ResultsPanel(coursePanel, quiz, studentAnswers);
            
            coursePanel.removeAll();
            coursePanel.add(rp);
            coursePanel.validate();
            coursePanel.repaint();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
