/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.*;
/**
 *
 * @author tylerliu
 */
public class ResultIcon extends javax.swing.JPanel {

    private boolean correct;
    private String studentAnswer;
    private Question question;
    /**
     * Creates new form ResultIcon
     */
    public ResultIcon(Question q, String studentAns, boolean correct) {
        initComponents();
        question = q;
        this.studentAnswer = studentAns;
        this.correct = correct;
        GridLayout gl = new GridLayout();
        gl.setColumns(1);
        gl.setRows(5);
        setLayout(gl);
        
        
        questionTxt.setText(question.getQuestionText());
        studentAnswerTxt.setText("Your Answer: " + studentAnswer);
        correctAnswer.setText("Correct Answer: " + question.getQuestionAnswer());
        //setMinimumSize(new Dimension(1, 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionTxt = new javax.swing.JTextField();
        studentAnswerTxt = new javax.swing.JTextField();
        correctAnswer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        questionTxt.setEditable(false);
        questionTxt.setText("jTextField1");
        questionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionTxtActionPerformed(evt);
            }
        });

        studentAnswerTxt.setEditable(false);
        studentAnswerTxt.setText("jTextField2");

        correctAnswer.setEditable(false);
        correctAnswer.setText("jTextField1");

        jButton1.setText("Show Steps");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(questionTxt)
            .addComponent(studentAnswerTxt)
            .addComponent(correctAnswer)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(questionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(studentAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(correctAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void questionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionTxtActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        System.out.println("show steps pressed");
        SolutionFrame sf = new SolutionFrame(question);
    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correctAnswer;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField questionTxt;
    private javax.swing.JTextField studentAnswerTxt;
    // End of variables declaration//GEN-END:variables
}
