/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.*;
import java.awt.*;
/**
 *
 * @author tylerliu
 */
public class ResultsPanel extends javax.swing.JPanel {

    private Quiz quiz;
    private CoursePanel coursePanel;
    private ArrayList<String> studentAnswers;
    private ArrayList<Boolean> correct;
    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel(CoursePanel coursePanel, Quiz quiz,ArrayList<String> sa) {
        initComponents();
        this.coursePanel = coursePanel;
        this.quiz = quiz;
        studentAnswers = sa;
        correct = checkAnswers();
        display();
    }
    
    private ArrayList<Boolean> checkAnswers() {
        ArrayList<Boolean> correct = new ArrayList<Boolean>();
        ArrayList<Question> questions = quiz.getQuestions();
        for (int i = 0; i < questions.size(); i++) {
            if (questions.get(i).getQuestionAnswer().equals(studentAnswers.get(i))) {
                correct.add(true);
            }
            else {
                correct.add(false);
            }
        }
        return correct;
    }
    
    private void display() {
        ArrayList<Question> questions = quiz.getQuestions();
        for (int i = 0; i < questions.size(); i++) {
            // TODO create GUI
            System.out.println(correct.get(i));
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
