/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.*;
/**
 *
 * @author tylerliu
 */
public class TopicIcon extends javax.swing.JPanel {

    private Topic topic;
    private CoursePanel coursePanel;
    /**
     * Creates new form TopicIcon
     */
    public TopicIcon(CoursePanel coursePanel, Topic topic) {
        initComponents();
        this.topic = topic;
        setTopicTxt(topic.getName());
        this.coursePanel = coursePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("jTextField1");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPressed
        System.out.println(topic.getName() + " pressed");
        Quiz quiz = topic.getQuiz();
        QuizPanel qp = new QuizPanel(quiz);
        
        coursePanel.removeAll();
        coursePanel.add(qp);
        coursePanel.validate();
        coursePanel.repaint();
    }//GEN-LAST:event_textPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    public void setTopicTxt(String name) {
        jTextField1.setText(name);
    }
}
